name: Call a reusable workflow and use its outputs

on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  job1:
    uses: ./.github/workflows/ttt1.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.first-word }} ${{ needs.job1.outputs.second-word }}
